version: '3'

services:
  site:
    build:
      context: .
      dockerfile: docker/nginx/nginx.dockerfile
    container_name: nginx2
    environment:
      - VIRTUAL_HOST=${APP_DOMAIN}
    ports:
      - ${LOCAL_PORT}:80
    volumes:
      - ./:/var/www/html:cached
    depends_on:
      - php
    networks:
      - app-network
  php:
    build:
      context: .
      dockerfile: docker/php/php.dockerfile
    container_name: php2
    volumes:
      - ./:/var/www/html:cached
    networks:
      - app-network
    ports:
      - 6001:6001

networks:
  app-network:
    driver: bridge
